development:
  adapter: postgresql
  encoding: utf8
  database: greensmoothie_development
  password:
  username: toddmiller
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: greensmoothie_test
  password:
  username: toddmiller
  pool: 5
  port: 5432
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: greensmoothie_production
  pool: 5
  port: 5432
